CREATE OR REPLACE FORCE EDITIONABLE VIEW "F1_ACCESS"."V_F1_CONSTRUCTORS" 
 ( "CONSTRUCTORID", "INFO", "NAME", "NATIONALITY"
  )  AS 
  select "CONSTRUCTORID","INFO","NAME","NATIONALITY" from F1_DATA.F1_CONSTRUCTORS