CREATE OR REPLACE FORCE EDITIONABLE VIEW "F1_ACCESS"."V_F1_TRACKS" 
 ( "CIRCUITID", "INFO", "CIRCUITNAME", "LAT", "LONGITUD", "LOCALITY", "COUNTRY"
  )  AS 
  select "CIRCUITID","INFO","CIRCUITNAME","LAT","LONGITUD","LOCALITY","COUNTRY" from F1_DATA.F1_TRACKS