CREATE OR REPLACE FORCE EDITIONABLE VIEW "F1_ACCESS"."V_F1_SEASONS_RACE_DATES" 
 ( "SEASON", "ROUND", "INFO", "RACENAME", "CIRCUITID", "URL", "CIRCUITNAME", "RACE_DATE"
  )  AS 
  select "SEASON","ROUND","INFO","RACENAME","CIRCUITID","URL","CIRCUITNAME","RACE_DATE" from F1_DATA.V_F1_SEASONS_RACE_DATES