CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_F1_DRIVERS" 
 ( "DRIVERID", "PERMANENTNUMBER", "CODE", "INFO", "GIVENNAME", "FAMILYNAME", "DATEOFBIRTH", "NATIONALITY"
  )  AS 
  select "DRIVERID","PERMANENTNUMBER","CODE","INFO","GIVENNAME","FAMILYNAME","DATEOFBIRTH","NATIONALITY" from F1_DATA.F1_DRIVERS