CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_F1_DRIVERSTANDINGS" 
 ( "SEASON", "RACE", "POSITION", "POSITIONTEXT", "POINTS", "WINS", "DRIVERID", "CONSTRUCTORID"
  )  AS 
  select "SEASON","RACE","POSITION","POSITIONTEXT","POINTS","WINS","DRIVERID","CONSTRUCTORID" from F1_DATA.F1_DRIVERSTANDINGS