CREATE OR REPLACE FORCE EDITIONABLE VIEW "F1_ACCESS"."V_F1_RACES" 
 ( "SEASON", "ROUND", "INFO", "RACENAME", "CIRCUITID"
  )  AS 
  select "SEASON","ROUND","INFO","RACENAME","CIRCUITID" from F1_DATA.F1_RACES