
   COMMENT ON COLUMN "F1_CONSTRUCTORS"."CONSTRUCTORID" IS 'Constructorname';
   COMMENT ON COLUMN "F1_CONSTRUCTORS"."INFO" IS 'Wikipedia link';
   COMMENT ON COLUMN "F1_CONSTRUCTORS"."NATIONALITY" IS 'Country origin';