--
-- Example SQL sqlite
--

-- CREATE INDEX IND_F1_OFFICIAL_TIMEDATA ON F1_OFFICIAL_TIMEDATA (SEASON,RACE,RACETYPE);

select SEASON
			,RACE
			,RACETYPE
			,DATAPOINT
			,TIME
			,DRIVER
			,DRIVERNUMBER
			,LAPTIME
			,(
					CAST(substr(LAPTIME, 1, 2) AS INTEGER) * 3600000 +   -- Hours to ms
					CAST(substr(LAPTIME, 4, 2) AS INTEGER) * 60000 +     -- Minutes to ms
					CAST(substr(LAPTIME, 7, 2) AS INTEGER) * 1000 +      -- Seconds to ms
					CAST(substr(LAPTIME, 10, 3) AS INTEGER)              -- Milliseconds
			) AS LAPTIME_MS
			,LAPNUMBER
			,STINT
			,PITOUTTIME
			,PITINTIME
			,SECTOR1TIME
			,SECTOR2TIME
			,SECTOR3TIME
			,SECTOR1SESSIONTIME
			,SECTOR2SESSIONTIME
			,SECTOR3SESSIONTIME
			,SPEEDI1
			,SPEEDI2
			,SPEEDFL
			,SPEEDST
			,ISPERSONALBEST
			,COMPOUND
			,TYRELIFE
			,FRESHTYRE
			,TEAM
			,LAPSTARTTIME
			,LAPSTARTDATE
			,TRACKSTATUS
			,POSITION
			,DELETED
			,DELETEDREASON
			,FATF1GENERATED
			,ISACCURATE
from F1_OFFICIAL_TIMEDATA
WHERE SEASON = 2025
      AND RACE = 4;