CREATE OR REPLACE FORCE EDITIONABLE VIEW "F1_REST_ACCESS"."V_F1_LAPTIMES" 
 ( "SEASON", "ROUND", "INFO", "RACENAME", "CIRCUITID", "URL", "CIRCUITNAME", "RACE_DATE", "RACE_TIME", "LAP_NUMBER", "DRIVERID", "POSITION", "LAPTIME"
  )  AS 
  select "SEASON","ROUND","INFO","RACENAME","CIRCUITID","URL","CIRCUITNAME","RACE_DATE","RACE_TIME","LAP_NUMBER","DRIVERID","POSITION","LAPTIME" from F1_DATA.V_F1_LAPTIMES