CREATE OR REPLACE FORCE EDITIONABLE VIEW "APEX_F1"."V_F1_RACES" 
 ( "SEASON", "ROUND", "INFO", "RACENAME", "CIRCUITID"
  )  AS 
  select "SEASON","ROUND","INFO","RACENAME","CIRCUITID" from f1_data.F1_RACES