CREATE OR REPLACE FORCE EDITIONABLE VIEW "APEX_F1"."V_F1_TRACKS" 
 ( "CIRCUITID", "INFO", "CIRCUITNAME", "LAT", "LONGITUD", "LOCALITY", "COUNTRY"
  )  AS 
  select "CIRCUITID","INFO","CIRCUITNAME","LAT","LONGITUD","LOCALITY","COUNTRY" from f1_data.F1_TRACKS