CREATE OR REPLACE FORCE EDITIONABLE VIEW "APEX_F1"."V_F1_QUALIFICATIONS" 
 ( "SEASON", "ROUND", "RACEDATE", "RACETIME", "POSITION", "DRIVERID", "CONSTRUCTORID", "Q1", "Q2", "Q3"
  )  AS 
  select "SEASON","ROUND","RACEDATE","RACETIME","POSITION","DRIVERID","CONSTRUCTORID","Q1","Q2","Q3" from f1_data.F1_QUALIFICATIONTIMES