CREATE OR REPLACE FORCE EDITIONABLE VIEW "APEX_F1"."V_F1_SEASONS_RACE_DATES" 
 ( "SEASON", "ROUND", "INFO", "RACENAME", "CIRCUITID", "URL", "CIRCUITNAME", "RACE_DATE"
  )  AS 
  select "SEASON","ROUND","INFO","RACENAME","CIRCUITID","URL","CIRCUITNAME","RACE_DATE" from f1_data.V_F1_SEASONS_RACE_DATES