CREATE OR REPLACE FORCE EDITIONABLE VIEW "APEX_F1"."V_F1_CONSTRUCTORSTANDINGS" 
 ( "SEASON", "RACE", "POSITION", "POSITIONTEXT", "POINTS", "WINS", "CONSTRUCTORID"
  )  AS 
  select "SEASON","RACE","POSITION","POSITIONTEXT","POINTS","WINS","CONSTRUCTORID" from f1_data.F1_CONSTRUCTORSTANDINGS