CREATE OR REPLACE FORCE EDITIONABLE VIEW "APEX_F1"."V_F1_LAPTIMES" 
 ( "SEASON", "ROUND", "RACE_DATE", "RACE_TIME", "LAP_NUMBER", "DRIVERID", "POSITION", "LAPTIME"
  )  AS 
  select "SEASON","ROUND","RACE_DATE","RACE_TIME","LAP_NUMBER","DRIVERID","POSITION","LAPTIME" from f1_data.F1_LAPTIMES