CREATE OR REPLACE FORCE EDITIONABLE VIEW "APEX_F1"."V_F1_DRIVERSTANDINGS" 
 ( "SEASON", "RACE", "POSITION", "POSITIONTEXT", "POINTS", "WINS", "DRIVERID", "CONSTRUCTORID"
  )  AS 
  select "SEASON","RACE","POSITION","POSITIONTEXT","POINTS","WINS","DRIVERID","CONSTRUCTORID" from f1_data.F1_DRIVERSTANDINGS