CREATE OR REPLACE FORCE EDITIONABLE VIEW "APEX_F1"."V_F1_OFFICIAL_WEATHER" 
 ( "YEAR", "RACE", "RACETYPE", "DATAPOINT", "TIME", "AIRTEMP", "HUMIDITY", "PRESSURE", "RAINFALL", "TRACKTEMP", "WINDDIRECTION", "WINDSPEED"
  )  AS 
  select "YEAR","RACE","RACETYPE","DATAPOINT","TIME","AIRTEMP","HUMIDITY","PRESSURE","RAINFALL","TRACKTEMP","WINDDIRECTION","WINDSPEED" from f1_data.F1_OFFICIAL_WEATHER