CREATE TABLE "F1_DRIVERSTANDINGS" 
   (	"SEASON" NUMBER(4,0), 
	"RACE" NUMBER(2,0), 
	"POSITION" NUMBER(3,0), 
	"POSITIONTEXT" VARCHAR2(3), 
	"POINTS" NUMBER(4,0), 
	"WINS" NUMBER(2,0), 
	"DRIVERID" VARCHAR2(30) NOT NULL ENABLE, 
	"CONSTRUCTORID" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;