CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_F1_DRIVERSTANDINGS" 
 ( "SEASON", "RACE", "POSITION", "POSITIONTEXT", "POINTS", "WINS", "DRIVERID", "PERMANENTNUMBER", "CODE", "INFO", "GIVENNAME", "FAMILYNAME", "DATEOFBIRTH", "NATIONALITY", "CONSTRUCTORID", "CONSTRUCTORINFO", "CONSTRUCTORNAME", "CONSTRUCTORNATIONALITY"
  )  AS 
  select "SEASON","RACE","POSITION","POSITIONTEXT","POINTS","WINS","DRIVERID","PERMANENTNUMBER","CODE","INFO","GIVENNAME","FAMILYNAME","DATEOFBIRTH","NATIONALITY","CONSTRUCTORID","CONSTRUCTORINFO","CONSTRUCTORNAME","CONSTRUCTORNATIONALITY" from F1_DATA.V_F1_DRIVERSTANDINGS