CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_F1_CONSTRUCTORSTANDINGS" 
 ( "SEASON", "RACE", "POSITION", "POSITIONTEXT", "POINTS", "WINS", "CONSTRUCTORID", "CONSTRUCTORINFO", "CONSTRUCTORNAME", "CONSTRUCTORNATIONALITY"
  )  AS 
  select "SEASON","RACE","POSITION","POSITIONTEXT","POINTS","WINS","CONSTRUCTORID","CONSTRUCTORINFO","CONSTRUCTORNAME","CONSTRUCTORNATIONALITY" from F1_DATA.V_F1_CONSTRUCTORSTANDINGS