-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:56:31 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:57:18 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_CONSTRUCTORS');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:57:53 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_CONSTRUCTORSTANDINGS');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:58:06 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_CUR_SEASON_STANDINGS');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:58:18 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_DRIVERS');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:58:30 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_DRIVERSTANDINGS');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:58:40 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_LAPTIMES');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:58:51 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_LAST_RACE_QUALIFIERS');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:58:59 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_LAST_RACE_RESULTS');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:59:08 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_LAST_RACE_WINNERS');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:59:19 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_OFFICIAL_TIMEDATA');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:59:27 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_OFFICIAL_WEATHER');

  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:59:39 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_QUALIFICATIONTIMES');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:59:48 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_RACES');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 13:59:57 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_RESULTS');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 14:00:07 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_SEASON');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 14:00:16 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_SEASONS_RACE_DATES');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 14:00:23 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_TRACKS');


  COMMIT; 
END;
/
-- Generated by Oracle SQL Developer REST Data Services 23.1.0.097.1607
-- Exported REST Definitions from ORDS Schema Version 22.4.4.r0411526
-- Schema: F1_REST_ACCESS   Date: Sat Aug 05 14:00:32 CEST 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'F1_REST_ACCESS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'f1_access',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.F1_REST_ACCESS.V_F1_UPCOMING_RACES');


  COMMIT; 
END;
/
