  CREATE TABLE "F1_DATA"."F1_CONSTRUCTORSTANDINGS" 
   (	"SEASON" NUMBER NOT NULL ENABLE,
	"RACE" NUMBER NOT NULL ENABLE,
	"POSITION" NUMBER,
	"POSITIONTEXT" VARCHAR2(10),
	"POINTS" NUMBER,
	"WINS" NUMBER,
	"CONSTRUCTORID" VARCHAR2(30),
	CONSTRAINT "F1_CONSTRUCTORSTANDINGS_FK1" FOREIGN KEY ("CONSTRUCTORID")
	 REFERENCES "F1_DATA"."F1_CONSTRUCTORS" ("CONSTRUCTORID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"