  CREATE TABLE "F1_DATA"."F1_LAPTIMES" 
   (	"SEASON" NUMBER,
	"ROUND" NUMBER,
	"RACE_DATE" DATE,
	"RACE_TIME" VARCHAR2(20),
	"LAP_NUMBER" NUMBER,
	"DRIVERID" VARCHAR2(30),
	"POSITION" NUMBER,
	"LAPTIME" VARCHAR2(20),
	CONSTRAINT "F1_LAPTIMES_FK2" FOREIGN KEY ("DRIVERID")
	 REFERENCES "F1_DATA"."F1_DRIVERS" ("DRIVERID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"