  CREATE TABLE "F1_DATA"."F1_OFFICIAL_TIMEDATA" 
   (	"SEASON" NUMBER(4,0),
	"RACE" NUMBER(2,0),
	"RACETYPE" VARCHAR2(3),
	"DATAPOINT" NUMBER(4,0),
	"TIME" VARCHAR2(20),
	"DRIVERNUMBER" NUMBER(2,0),
	"LAPTIME" VARCHAR2(20),
	"LAPNUMBER" NUMBER(3,0),
	"STINT" NUMBER(3,0),
	"PITOUTTIME" VARCHAR2(20),
	"PITINTIME" VARCHAR2(20),
	"SECTOR1TIME" VARCHAR2(20),
	"SECTOR2TIME" VARCHAR2(20),
	"SECTOR3TIME" VARCHAR2(20),
	"SECTOR1SESSIONTIME" VARCHAR2(20),
	"SECTOR2SESSIONTIME" VARCHAR2(20),
	"SECTOR3SESSIONTIME" VARCHAR2(20),
	"SPEEDI1" NUMBER(4,1),
	"SPEEDI2" NUMBER(4,1),
	"SPEEDFL" NUMBER(4,1),
	"SPEEDST" NUMBER(4,1),
	"ISPERSONALBEST" VARCHAR2(5),
	"COMPOUND" VARCHAR2(20),
	"TYRELIFE" NUMBER(3,1),
	"FRESHTYRE" VARCHAR2(5),
	"LAPSTARTTIME" VARCHAR2(20),
	"TEAM" VARCHAR2(20),
	"DRIVER" VARCHAR2(5),
	"TRACKSTATUS" NUMBER(3,0),
	"ISACCURATE" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"