  CREATE TABLE "F1_DATA"."F1_RACES" 
   (	"SEASON" NUMBER NOT NULL ENABLE,
	"ROUND" NUMBER NOT NULL ENABLE,
	"INFO" VARCHAR2(100) NOT NULL ENABLE,
	"RACENAME" VARCHAR2(100) NOT NULL ENABLE,
	"CIRCUITID" VARCHAR2(30) NOT NULL ENABLE,
	CONSTRAINT "F1_RACES_FK1" FOREIGN KEY ("CIRCUITID")
	 REFERENCES "F1_DATA"."F1_TRACKS" ("CIRCUITID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"