REM INSERTING into F1_STAGING.F1_JSON_DOCTYPE
SET DEFINE OFF;
Insert into F1_STAGING.F1_JSON_DOCTYPE (ID,DOC_TYPE) values ('1','CONSTRUCTORS');
Insert into F1_STAGING.F1_JSON_DOCTYPE (ID,DOC_TYPE) values ('2','CONSTRUCTORSTANDINGS');
Insert into F1_STAGING.F1_JSON_DOCTYPE (ID,DOC_TYPE) values ('3','DRIVERS');
Insert into F1_STAGING.F1_JSON_DOCTYPE (ID,DOC_TYPE) values ('4','DRIVERSSTANDINGS');
Insert into F1_STAGING.F1_JSON_DOCTYPE (ID,DOC_TYPE) values ('5','LAPTIMES');
Insert into F1_STAGING.F1_JSON_DOCTYPE (ID,DOC_TYPE) values ('6','QUALIFICATIONS');
Insert into F1_STAGING.F1_JSON_DOCTYPE (ID,DOC_TYPE) values ('7','RACES');
Insert into F1_STAGING.F1_JSON_DOCTYPE (ID,DOC_TYPE) values ('8','RACERESULTS');
Insert into F1_STAGING.F1_JSON_DOCTYPE (ID,DOC_TYPE) values ('9','SEASONS');
Insert into F1_STAGING.F1_JSON_DOCTYPE (ID,DOC_TYPE) values ('10','RACEDATES');
Insert into F1_STAGING.F1_JSON_DOCTYPE (ID,DOC_TYPE) values ('11','TRACKS');
commit;