REM INSERTING into F1_STAGING.F1_JSON_RACETYPE
SET DEFINE OFF;
Insert into F1_STAGING.F1_JSON_RACETYPE (ID,RACE_TYPE) values ('1','FP');
Insert into F1_STAGING.F1_JSON_RACETYPE (ID,RACE_TYPE) values ('2','Q');
Insert into F1_STAGING.F1_JSON_RACETYPE (ID,RACE_TYPE) values ('3','R');
commit;